name: Deploy landing page to Azure Static Web Apps

on:
  push:
    branches:
      - master
    paths:
      - 'apps/landing/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - 'apps/landing/**'
      - 'packages/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install root dependencies
        run: |
          npm install -g npm@latest
          npm install
          npm run build-common

      - name: Build And Deploy
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: /apps/landing
          skip_app_build: true
          skip_api_build: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_LANDING_PAGE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'close'
