name: 'Deploy client to Storage Blob'

on:
  push:
    brances:
      - 'master'
      # delete this
      - 'standalone-api'
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: 'Run tests'
        working-directory: 'client'
        run: npm run test

      - name: 'Generate static site'
        working-directory: 'client'
        run: |
          'npm run generate'
        env:
          NODE_ENV: 'production'
          BASE_URL: 'https://api.onlinetipovacka.sk/api'

      - uses: 'azure/login@v1'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Upload to blob storage'
        uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.0.72
          inlineScript: |
            'az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -d '$web' -s ./client'

      - name: 'Purge CDN endpoint'
        uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.0.72
          inlineScript: |
            'az cdn endpoint purge --content-paths  "/*" --profile-name ${{ secrets.CDN_PROFILE_NAME }} --name ${{ secrets.CDN_ENDPOINT }} --resource-group onlinetipovacka'

      - name: 'Azure Logout'
        run: |
          'az logout'
