name: Deploy API to Azure Container Apps

on:
  push:
    branches: [master]
    paths:
      - 'Dockerfile-api'
      - 'apps/api/**'
      - 'packages/**'

  # Allow mannually trigger
  workflow_dispatch:

env:
  IMAGE_NAME: tipovacka-api
  CONTAINER_REGISTRY_NAME: crtipovackashared
  RESOURCE_GROUP_NAME: rg-tipovacka-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.TIPOVACKA_REGISTRY_USERNAME }}
          password: ${{ secrets.TIPOVACKA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile-api
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TIPOVACKA_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ${{ env.IMAGE_NAME }} -g ${{ env.RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io --username  ${{ secrets.TIPOVACKA_REGISTRY_USERNAME }} --password ${{ secrets.TIPOVACKA_REGISTRY_PASSWORD }}
            az containerapp update -n ${{ env.IMAGE_NAME }} -g ${{ env.RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.s{ha} }}
