name: Deploy API to Azure Container Apps

on:
  push:
    branches: [master]
    paths:
      - 'apps/api/**'
      - 'packages/**'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: tipovacka.azurecr.io
          username: ${{ secrets.TIPOVACKA_REGISTRY_USERNAME }}
          password: ${{ secrets.TIPOVACKA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tipovacka.azurecr.io/tipovacka:${{ github.sha }}
          file: ./Dockerfile-api
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TIPOVACKA_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tipovacka -g tipovacka --server tipovacka.azurecr.io --username  ${{ secrets.TIPOVACKA_REGISTRY_USERNAME }} --password ${{ secrets.TIPOVACKA_REGISTRY_PASSWORD }}
            az containerapp update -n tipovacka -g tipovacka --image tipovacka.azurecr.io/tipovacka:${{ github.sha }}
