name: 'Deploy client to Storage Blob'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/client/**'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Upgrade npm to 8.x
        run: npm i -g npm@8

      - name: 'Install dependencies'
        run: npm install

      - name: 'Generate static site'
        run: |
          npm run build-common
          npm run generate --workspace=@tipovacka/client
        env:
          NODE_ENV: 'production'
          BASE_URL: 'https://api.onlinetipovacka.sk/api'

      - uses: 'azure/login@v1'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Upload to blob storage'
        uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -d '$web' -s ./apps/client/dist/

      - name: 'Purge CDN endpoint'
        uses: 'azure/CLI@v1'
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{ secrets.CDN_PROFILE_NAME }} --name ${{ secrets.CDN_ENDPOINT }} --resource-group tipovacka

      - name: 'Azure Logout'
        run: |
          az logout
