# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - onlinetipovacka

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://onlinetipovacka.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_79652d7c45334eddb4e22ca105cf219e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b239b0132512450eb8453fe2eca5b29d }}

    - run: |
        docker build . -t onlinetipovacka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79652d7c45334eddb4e22ca105cf219e }}/onlinetipovacka/onlinetipovacka:${{ github.sha }}
        docker push onlinetipovacka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79652d7c45334eddb4e22ca105cf219e }}/onlinetipovacka/onlinetipovacka:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'onlinetipovacka'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c094b755e1e4009a6adb367e729bb4a }}
        images: 'onlinetipovacka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_79652d7c45334eddb4e22ca105cf219e }}/onlinetipovacka/onlinetipovacka:${{ github.sha }}'